import type { NextPage } from "next";
import Head from "next/head";
import { Hero } from "@/components/Hero";
import { Clips } from "@/components/Clips";
import { Heading } from "@/components/Heading";

export const getStaticPaths = async () => {
  return {
    paths: [],
    fallback: true,
  };
};

export const getStaticProps = async () => {
  return {
    props: {},
  };
};

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="max-w-[1920px] mx-auto">
        <Hero />
        <Heading
          headline="BY CHANGING NOTHING, SHE CHANGED EVERYTHING"
          description="Serena’s never been defined by just one thing. And only the Queen could inspire us to
          rally and rejoice at every deuce, design and dare-to-be-more moment. It began on the
          court and lives on with a new era of statement-makers."
          href="/"
          linkText="Explore the Collection"
        />
        <Clips />
      </div>
    </div>
  );
};

export default Home;
